In [125]:
import pandas as pd
import numpy as np

In [128]:
df = pd.read_csv('titanic.csv')
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN      NaN  
887      0            112053  30.0000   B42      B42  
888      2        W./C. 6607  23.4500   NaN      NaN  
889      0            111369  30.0000  C148     C148  
890      0            370376   7.7500   NaN      NaN  

[891 rows x 12 columns]

In [129]:
df_n = df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns')
df_n

Survived  Pclass     Sex   Age     Fare
0           0       3    male  22.0   7.2500
1           1       1  female  38.0  71.2833
2           1       3  female  26.0   7.9250
3           1       1  female  35.0  53.1000
4           0       3    male  35.0   8.0500
..        ...     ...     ...   ...      ...
886         0       2    male  27.0  13.0000
887         1       1  female  19.0  30.0000
888         0       3  female   NaN  23.4500
889         1       1    male  26.0  30.0000
890         0       3    male  32.0   7.7500

[891 rows x 5 columns]

In [130]:
df_n.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
Fare          0
dtype: int64

In [131]:
import math
median_Age = math.floor(df_n.Age.median())

In [132]:
Age_n = df['Age'].fillna(median_Age)
new_df = df_n.drop(['Age'],axis='columns')
new_df 

Survived  Pclass     Sex     Fare
0           0       3    male   7.2500
1           1       1  female  71.2833
2           1       3  female   7.9250
3           1       1  female  53.1000
4           0       3    male   8.0500
..        ...     ...     ...      ...
886         0       2    male  13.0000
887         1       1  female  30.0000
888         0       3  female  23.4500
889         1       1    male  30.0000
890         0       3    male   7.7500

[891 rows x 4 columns]

In [133]:
dummies = pd.get_dummies(new_df.Sex)
dummies.head()

female  male
0       0     1
1       1     0
2       1     0
3       1     0
4       0     1

In [134]:
sex_n = []
for i in new_df.Sex:
    if i == 'male':
        sex_n.append(0)
    elif i == 'female':
        sex_n.append(1)

        
# removing sex columns 
inputs_n = new_df.drop(['Sex','Survived'],axis='columns')
# adding sex column with bit digit those value add in sex_n array
inputs_n["Sex"] = sex_n

In [135]:
inputs_n

Pclass     Fare  Sex
0         3   7.2500    0
1         1  71.2833    1
2         3   7.9250    1
3         1  53.1000    1
4         3   8.0500    0
..      ...      ...  ...
886       2  13.0000    0
887       1  30.0000    1
888       3  23.4500    1
889       1  30.0000    0
890       3   7.7500    0

[891 rows x 3 columns]

In [136]:
target = df.Survived
inputs_n['Age'] = Age_n

In [137]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs_n[['Pclass','Age','Fare','Sex']],target,test_size=0.2)

In [138]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()

In [139]:
model.fit(X_train,y_train)

GaussianNB()

In [153]:
model.score(X_test,y_test)

0.7932960893854749

In [141]:
model.predict(X_test)

array([0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1], dtype=int64)

In [147]:
p = model.predict(inputs_n[['Pclass','Age','Fare','Sex']])

In [149]:
inputs_n['Survived_n'] = p

In [150]:
inputs_n

Pclass     Fare  Sex   Age  Survived_n
0         3   7.2500    0  22.0           0
1         1  71.2833    1  38.0           1
2         3   7.9250    1  26.0           1
3         1  53.1000    1  35.0           1
4         3   8.0500    0  35.0           0
..      ...      ...  ...   ...         ...
886       2  13.0000    0  27.0           0
887       1  30.0000    1  19.0           1
888       3  23.4500    1  28.0           1
889       1  30.0000    0  26.0           0
890       3   7.7500    0  32.0           0

[891 rows x 5 columns]

In [151]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN      NaN  
887      0            112053  30.0000   B42      B42  
888      2        W./C. 6607  23.4500   NaN      NaN  
889      0            111369  30.0000  C148     C148  
890      0            370376   7.7500   NaN      NaN  

[891 rows x 12 columns]

In [188]:
# Email Spam Exercise
esdf = pd.read_csv('emailSpam.csv')

In [189]:
esdf

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [190]:
esdf.isnull().sum()

Category    0
Message     0
dtype: int64

In [191]:
Category_n = []
for i in esdf.Category:
    if i == "ham":
        Category_n.append(1)
    elif i == "spam":
        Category_n.append(0)
print(Category_n)
len(Category_n)

[1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 

5572

In [192]:
esdf['Category_n'] = Category_n
esdf

Category                                            Message  Category_n
0         ham  Go until jurong point, crazy.. Available only ...           1
1         ham                      Ok lar... Joking wif u oni...           1
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...           0
3         ham  U dun say so early hor... U c already then say...           1
4         ham  Nah I don't think he goes to usf, he lives aro...           1
...       ...                                                ...         ...
5567     spam  This is the 2nd time we have tried 2 contact u...           0
5568      ham               Will ü b going to esplanade fr home?           1
5569      ham  Pity, * was in mood for that. So...any other s...           1
5570      ham  The guy did some bitching but I acted like i'd...           1
5571      ham                         Rofl. Its true to its name           1

[5572 rows x 3 columns]

In [193]:
X_train, X_test, y_train, y_test = train_test_split(esdf.Message,esdf.Category_n,test_size=0.2)

In [194]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_count = v.fit_transform(X_train.values)
X_train_count.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [195]:
# When we get the data that's certain frequenct then we will use Mutlinomial Naive Bayes
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count,y_train)

MultinomialNB()

In [196]:
email = ['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...']
email_count = v.transform(email)
model.predict(email_count)

array([1], dtype=int64)

In [197]:
X_test_count = v.transform(X_test)
print(f'Training data score {model.score(X_train_count,y_train)} Testing Data Score {model.score(X_test_count,y_test)}')

Training data score 0.9937177473636976 Testing Data Score 0.9838565022421525


In [198]:
Category_n_predict = v.transform(esdf.Message)
p = model.predict(Category_n_predict)

In [199]:
esdf['Category_n_p'] = p

In [200]:
esdf

Category                                            Message  Category_n  \
0         ham  Go until jurong point, crazy.. Available only ...           1   
1         ham                      Ok lar... Joking wif u oni...           1   
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...           0   
3         ham  U dun say so early hor... U c already then say...           1   
4         ham  Nah I don't think he goes to usf, he lives aro...           1   
...       ...                                                ...         ...   
5567     spam  This is the 2nd time we have tried 2 contact u...           0   
5568      ham               Will ü b going to esplanade fr home?           1   
5569      ham  Pity, * was in mood for that. So...any other s...           1   
5570      ham  The guy did some bitching but I acted like i'd...           1   
5571      ham                         Rofl. Its true to its name           1   

      Category_n_p  
0                1  
1                1  
2                0  
3                1  
4                1  
...            ...  
5567             0  
5568             1  
5569             1  
5570             1  
5571             1  

[5572 rows x 4 columns]

In [210]:
email = ['Hy this is my email. I wanna to talk to you']
email_count = v.transform(email)
model.predict(email_count)    

array([1], dtype=int64)

In [215]:
email = ['''
Hello samid samid,



Thank you for using Surview. We hope you love it! If you do, would you consider posting a Google online review? This helps us to continue providing great services and helps potential clients to make confident decisions.



Thank you in advance for your review and being preferred customer.



Kind Regards,

Surview Team
''']
email_count = v.transform(email)
model.predict(email_count) 

array([1], dtype=int64)